name: Deploy Frontend

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  terraform-apply:
    name: Apply Terraform configuration
    runs-on: ubuntu-latest

    env:   
      AWS_REGION: ${{ secrets.AWS_REGION }}    # You can also store the region in a secret if needed
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_TECHNEWS_YAN }}  
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_TECHNEWS_YAN }}  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}  
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}  
          aws-region: ${{ env.AWS_REGION }}  

     
      # Run Terraform in ./frontend directory
      - name: Initialize Terraform (Frontend)
        run: terraform init
        working-directory: ./frontend

      - name: Terraform Plan (Frontend)
        run: terraform plan
        working-directory: ./frontend

      - name: Terraform Apply (Frontend)
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve
        working-directory: ./frontend

    